import Head from "next/head";
import Test from "~/components/TestComponent";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col items-center">
        <div className="w-2/3">
            <Test title={"Out Story"} />
        </div>
        </div>
      </main>
    </>
  )
}
